version: '3.9'

services:
  aesm:
    image: ghcr.io/initc3/sgx-aesm:2.19-buster
    volumes:
      - aesmd-socket:/var/run/aesmd
    devices:
      - /dev/isgx

  genquote:
    image: sgx_hashmachine
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - aesm
    devices:
      - /dev/isgx
    environment:
      SGX_SPID: ${SGX_SPID}
      IAS_PRIMARY_KEY: ${IAS_PRIMARY_KEY}
      INFURA_API_KEY: ${INFURA_API_KEY}
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./settings:/usr/src/hashmachine/settings
      - ./epidcontest.py:/usr/src/hashmachine/epidcontest.py
      - ./epid_contest_contract_abi.txt:/usr/src/hashmachine/epid_contest_contract_abi.txt
    command: ./run-client --debug -q

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
