version: '3.9'

services:
  aesm:
    image: ghcr.io/initc3/sgx-aesm:2.19-buster
    volumes:
      - aesmd-socket:/var/run/aesmd
    devices:
      - /dev/isgx

  genquote:
    image: teehash
    build:
      context: .
      dockerfile: x.Dockerfile
    depends_on:
      - aesm
    devices:
      - /dev/isgx
    environment:
      SGX_SPID: ${SGX_SPID}
      IAS_PRIMARY_KEY: ${IAS_PRIMARY_KEY}
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./result/bin/Enclave.signed.so:/usr/src/hashmachine/Enclave.signed.so
    command: ./run-client --debug -q

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
